#In this advanced example, we create an elastigroup with
#  - user data and shutdown script
#  - multiple EBS device mappings for the instances in this group
#  - network interfaces configuration for the instances in this group
#  - revert to spot configuration, which is the time frame at which Spotinst tries to spin spots instead of on-demands
#  - preferred availability zones in which to spin instances
#  - preferred spot instance types to launch

- hosts: localhost
  tasks:
    - name: create elastigroup
      spotinst_aws_elastigroup:
          name: ansible_test_group
          state: present
          risk: 100
          availability_vs_cost: balanced
          revert_to_spot:
            perform_at: timeWindow
            time_windows:
              - "Sun:11:00-Mon:12:00"
              - "Mon:03:00-Wed:02:30"
          availability_zones:
            - name: us-east-2c
              subnet_id: subnet-123c
            - name: us-east-2b
              subnet_id: subnet-123b
            - name: us-east-2a
              subnet_id: subnet-123a
          image_id: test-ami
          key_pair: test-key-pair
          max_size: 2
          min_size: 0
          target: 0
          unit: instance
          monitoring: False
          on_demand_instance_type: m4.large
          product: Linux/UNIX
          user_data: IyEvdXNyL2Jpbi9lbnYgYmFzaA==
          shutdown_script: IyEvdXNyL2Jpbi9lbnYgYmFzaA==
          preferred_availability_zones:
            - us-east-2c
          block_device_mappings:
            - device_name: '/dev/xvda'
              ebs:
                volume_size: 60
                volume_type: gp2
            - device_name: '/dev/xvdb'
              ebs:
                volume_size: 120
                volume_type: gp2
            - device_name: '/dev/xvdc'
              virtual_name: ephemeral0
          network_interfaces:
            - description: test-eni
              device_index: 0
              associate_public_ip_address: true
              delete_on_termination: true
              associate_ipv6_address: false
            - description: test-eni
              device_index: 1
              associate_public_ip_address: false
              delete_on_termination: true
              associate_ipv6_address: false
          tags:
            - Name: ansible_test_group
            - Environment: dev
          security_group_ids:
            - sg-default
          spot_instance_types:
            - m4.xlarge
            - m5.xlarge
          preferred_spot_instance_types:
            - m4.xlarge
          do_not_update:
            - image_id
            - target
            - user_data
      register: result
    - debug: var=result
