#Integrate and Spotinst elastigroup with AWS's ECS

- hosts: localhost
  tasks:
    - name: create elastigroup
      spotinst_aws_elastigroup:
          account_id: 
          token: 
          name: ansible_ecs_group
          state: absent
          risk: 100
          availability_vs_cost: balanced
          availability_zones:
            - name: us-west-2b
              subnet_id: subnet-1ba25052
          image_id: ami-f173cc91
          key_pair: Noam-key
          max_size: 2
          min_size: 0
          target: 0
          unit: instance
          monitoring: False
          on_demand_instance_type: m4.large
          product: Linux/UNIX
          ecs:
            cluster_name: test-cluster-name
            auto_scale:
              is_enabled: true
              is_auto_config: false
              cooldown: 300
              headroom:
                cpu_per_unit: 100
                memory_per_unit: 100
                num_of_units: 100
              attributes:
                - key: test_key
                  value: test_value
                - key: test_key1
                  value: test_value1
              down:
            evaluation_periods: 3
          tags:
            - Name: ansible_test_group
            - Environment: dev
          security_group_ids:
            - sg-default
          spot_instance_types:
            - m4.xlarge
            - m5.xlarge
          do_not_update:
            - image_id
            - target
            - user_data
      register: result
    - debug: var=result
