
#Integrate and Spotinst elastigroup with AWS's Route53
- hosts: localhost
  tasks:
    - name: create elastigroup
      spotinst_aws_elastigroup:
          account_id: 
          token: 
          name: ansible_route53_test_group
          state: absent
          risk: 100
          availability_vs_cost: balanced
          availability_zones:
            - name: us-west-2b
              subnet_id: subnet-1ba25052
          image_id: ami-f173cc91
          key_pair: Noam-key
          max_size: 2
          min_size: 0
          target: 0
          unit: instance
          monitoring: False
          on_demand_instance_type: m4.large
          product: Linux/UNIX
          route53:
            domains:
              - hosted_zone_id: abc234
                record_sets:
                  - name: test-hosted-zone1
                    use_public_ip: true
                  - name: test1
                    use_public_ip: false
              - hosted_zone_id: abc123
                record_sets:
                  - name: test-hosted-zone2
                    use_public_ip: false
                  - name: test2
                    use_public_ip: true
          tags:
            - Name: ansible_test_group
            - Environment: dev
          security_group_ids:
            - sg-default
          spot_instance_types:
            - m4.xlarge
            - m5.xlarge
          do_not_update:
            - image_id
            - target
            - user_data
      register: result
    - debug: var=result