#Integrate and Spotinst elastigroup with AWS's ElasticBeanstalk
- hosts: localhost
  tasks:
    - name: create elastigroup
      spotinst_aws_elastigroup:
          account_id: 
          token: 
          name: ansible_elasticbeanstalk_group
          state: absent
          risk: 100
          availability_vs_cost: balanced
          availability_zones:
            - name: us-west-2b
              subnet_id: subnet-1ba25052
          image_id: ami-f173cc91
          key_pair: Noam-key
          max_size: 2
          min_size: 0
          target: 0
          unit: instance
          monitoring: False
          on_demand_instance_type: m4.large
          product: Linux/UNIX
          elastic_beanstalk:
            environment_id: e-3tkmbj7hzc
            deployment_preferences:
              automatic_roll: true
              batch_size_percentage: 50
              grace_period: 600
              strategy:
                action: REPLACE_SERVER
                should_drain_instances: true
          tags:
            - Name: ansible_test_group
            - Environment: dev
          security_group_ids:
            - sg-default
          spot_instance_types:
            - m4.xlarge
            - m5.xlarge
          do_not_update:
            - image_id
            - target
            - user_data
      register: result
    - debug: var=result